AdressProject/Models/Adress.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AdressProject.Models
{
    public class Adress
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Field cannot be empty")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Name Max Length is 20, Min Length 2")]

        public string Name { get; set; }
        [Required(ErrorMessage = "Field cannot be empty")]
        [StringLength(20,MinimumLength =2, ErrorMessage = "Surname Max Length is 20, Min Length 2")]

        public string SurName { get; set; }
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Phone number must be 11 digits")]

        public string PhoneNumber { get; set; }
        [StringLength(100, ErrorMessage = "Description Max Length is 100")]
        public string Adres { get; set; }

        public int AdressTypeId { get; set; }

        public virtual AdressType AdressType { get; set; }
    }
}

AdressProject/Models/AdressType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdressProject.Models
{
    public class AdressType
    {
        public int AdressTypeId { get; set; }

        public string AdressTipi { get; set; }

    }
}

AdressProject/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdressProject.Models
{
    public class Context:DbContext
    {

        public Context(DbContextOptions<Context> options) : base(options)
        {

        }

       public DbSet<Adress> Adresses { get; set; }

       public DbSet<AdressType> AdressTypes { get; set; }

    }
}

AdressProject/Models/ErrorViewModel.cs
using System;

namespace AdressProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdressProject/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdressProject.Models
{
    public class SeedData
    {


        public static void Initialize(IServiceProvider serviceProvider)
        {

            using (var Context = new Context(serviceProvider.GetRequiredService<DbContextOptions<Context>>()))
            {
                if (Context.Adresses.Any())
                {
                    return;
                }
                Context.Adresses.AddRange(
                    new Adress { Name = "Ebru", SurName = "Şahin", PhoneNumber = "05452078669", Adres="Emek Mah, Ekrem Sok Darıca/Kocaeli", AdressType = new AdressType() { AdressTipi = "Ev" } },
                   new Adress { Name = "Anıl", SurName = "Demiroğlu", PhoneNumber = "05538240952", Adres = "Hürriyet Mah,Trump Tower Mecidiyeköy/İstanbul", AdressType = new AdressType() { AdressTipi = "İş" } },
                   new Adress { Name = "Buğra", SurName = "Kaplan", PhoneNumber = "05538241238", Adres = "İstiklal Mah, Papatya sok, Şişli/İstanbul", AdressType = new AdressType() { AdressTipi = "Okul" } },
                   new Adress { Name = "Selin", SurName = "Çolak", PhoneNumber = "05534560958", Adres = "Muratpaşa Mah, Fikribey apt, Üsküdar/İstanbul", AdressType = new AdressType() { AdressTipi = "Evv" } }
                    );

                Context.SaveChanges();
            }

        }
    }
}

AdressProject/Controllers/AdressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdressProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AdressProject.Controllers
{
    public class AdressController : Controller
    {
        // GET: Adress

        private Context con;

        public AdressController(Context con)
        {
            this.con = con;
        }
        public ActionResult Index()
        {
            var list = con.Adresses.ToList();
            var f = con.Adresses.Include(p => p.AdressType).ToList();
            return View(f);
        }

        // GET: Adress/Details/5
        public ActionResult Details(int id)
        {
            var f = con.Adresses.Include(p => p.AdressType).Where(x => x.Id == id).FirstOrDefault();
            return View(f);
        }

        // GET: Adress/Create
        public ActionResult Create()
        {
            ViewBag.AdressTypess = new SelectList(con.AdressTypes, "AdressTypeId", "AdressTipi");
            return View();
        }

        // POST: Adress/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here Adress p = new Adress();
                Adress p = new Adress();
                //p.Id = Convert.ToInt32(collection["Id"]);
                p.Name = collection["Name"];
                p.SurName = collection["SurName"];
                p.PhoneNumber = collection["PhoneNumber"];
                p.Adres = collection["Adres"];
                
                //con.Adresses.Update(p);
                Microsoft.Extensions.Primitives.StringValues f;
                if (collection.TryGetValue("AdressType", out f))
                {
                    p.AdressType = new AdressType() { AdressTypeId = Convert.ToInt32(f[0]) };

                }
                con.Entry(p).State = EntityState.Added;
                con.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Adress/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.AdressTypess = new SelectList(con.AdressTypes, "AdressTypeId", "AdressTipi");
            var f = con.Adresses.Include(p => p.AdressType).Where(x => x.Id == id).FirstOrDefault();
            return View(f);
        }

        // POST: Adress/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection, Adress dd)
        {
            try
            {
                // TODO: Add update logic here
                Adress p = new Adress();
                p.Id = Convert.ToInt32(collection["Id"]);
                p.Name = collection["Name"];
                p.SurName = collection["SurName"];
                p.PhoneNumber= collection["PhoneNumber"];
                p.Adres= collection["Adres"];
                p.AdressTypeId = dd.AdressType.AdressTypeId;
                con.Adresses.Update(p);

                con.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Adress/Delete/5
        public ActionResult Delete(int id)
        {
            var f = con.Adresses.Include(p => p.AdressType).Where(x => x.Id == id).FirstOrDefault();
            return View(f);
        }

        // POST: Adress/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var f = con.Adresses.Find(id);

                con.Adresses.Remove(f);
                con.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AdressProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AdressProject.Models;

namespace AdressProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdressProject/Views/Adress/Create.cshtml
@model AdressProject.Models.Adress

<h4>Adress</h4>
<hr />
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SurName" class="control-label"></label>
                    <input asp-for="SurName" class="form-control" />
                    <span asp-validation-for="SurName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Adres" class="control-label"></label>
                    <input asp-for="Adres" class="form-control" />
                    <span asp-validation-for="Adres" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdressTypeId" class="control-label"></label>
                    <select asp-for="@Model.AdressType" class="form-control" asp-items="ViewBag.AdressTypess"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdressProject/Views/Adress/Delete.cshtml
@model AdressProject.Models.Adress

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Adress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SurName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SurName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdressType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdressType.AdressTipi)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AdressProject/Views/Adress/Details.cshtml
@model AdressProject.Models.Adress

<div>
    <h4>Adress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SurName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SurName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdressType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdressType.AdressTipi)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AdressProject/Views/Adress/Edit.cshtml
@model AdressProject.Models.Adress

<h4>Adress</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SurName" class="control-label"></label>
                <input asp-for="SurName" class="form-control" />
                <span asp-validation-for="SurName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adres" class="control-label"></label>
                <input asp-for="Adres" class="form-control" />
                <span asp-validation-for="Adres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdressTypeId" class="control-label"></label>
                <select asp-for="@Model.AdressType.AdressTypeId" class="form-control" asp-items="ViewBag.AdressTypess"></select>
                <span asp-validation-for="AdressTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AdressProject/Views/Adress/Index.cshtml
@model IEnumerable<AdressProject.Models.Adress>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                NO
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SurName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adres)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdressType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{int sayac = 1; }
@foreach (var item in Model) {
        <tr>
            <td>
                @sayac
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SurName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdressType.AdressTypeId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    sayac++;
}
    </tbody>
</table>

AdressProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
   
</div>

AdressProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdressProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/simple-sidebar.css" rel="stylesheet">
</head>
<body>
    
    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Adress Book </div>
            <div class="list-group list-group-flush">



                <a asp-action="Index" asp-controller="Adress" class="nav-link"><i class="fas fa-fw fa-tachometer-alt"></i><span> Adresses</span> </a>

                @*<a href="#" class="list-group-item list-group-item-action bg-light">Shortcuts</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Overview</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Events</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Profile</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Status</a>*@
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        
        
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    @*<div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                </div>*@
                </nav>


                @RenderBody()
                <!--buraya yazılacak-->
            </div>
            <!-- /#page-content-wrapper -->

        </div>
        <!-- /#wrapper -->
   
    
    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>




   



   
</body>
</html>